name: Package the application and upload it to AWS EC2.

# Install git, npm, pm2 firstly on the EC2 instance.

on:
    workflow_dispatch: # trigger the workflow manually
    push:
        branches:
            - main
            - release/*

jobs:
    build:
        # runs-on Specify the virtual machine environment required to run the designated job task (required field).
        runs-on: ubuntu-latest
        steps:
            # Get the source code
            - name: Code Checkout
              # Use the action library `actions/checkout` to checkout the source code.
              uses: actions/checkout@main

            - name: Install node.js
              # Use the action library `actions/setup-node` to install node
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x

            - name: Install dependencies
              run: npm install

            - name: Code packaging
              run: npm run build

            - name: Release to AWS EC2
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.REMOTE_HOST }}
                username: ${{ secrets.REMOTE_USER }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                script: |
                  cd /home/ec2-user/workspace/shadcn-admin-template
                  git pull
                  npm install
                  npm run build
                  pm2 restart shadcn-admin-template
                  
                # `git pull`, which means you already have a repo on the server
                # `pm2 restart`, which means you have already run pm2 start when preparing the environment 
                # sudo npm install pm2 -g | npm install pm2 -D
                # [npx] pm2 start npm --name shadcn-admin-template -- run start -- -p 3000
                # [npx] pm2 list nextjs-app
                # [npx] pm2 stop shadcn-admin-template  
                # [npx] pm2 restart shadcn-admin-template
                # [npx] pm2 delete shadcn-admin-template
                # Refer to: 
                  # https://dev.to/yousufbasir/automating-nextjs-application-deployment-with-github-actions-38ac
                  # https://medium.com/@mudasirhaji/deploying-a-next-js-app-manually-on-aws-ec2-a-step-by-step-guide-58b266ff1c52